channels:
- conda-forge
dependencies:
- python=3.11.8
- pip<=24.1.2
- pip:
  - mlflow==2.12.2
  - attrs==23.1.0
  - click==8.1.7
  - colorama==0.4.6
  - google-cloud-bigquery==3.21.0
  - jinja2==3.1.2
  - numpy==1.25.2
  - packaging==23.2
  - pandas==2.2.1
  - pathlib==1.0.1
  - protobuf==4.25.3
  - pyyaml==6.0.1
  - requests==2.32.3
  - ruamel-yaml-clib==0.2.8
  - ruamel-yaml==0.18.6
  - spacy==3.7.5
name: mlflow-env
